import {SITE,projects,skills} from "@/lib/content";import {Wrap,Heading,Btn,ProjectCard} from "@/components/ui";import Link from "next/link";import Image from "next/image";
const services=[["Social Media","Content strategy, social creatives, captions and brand communication."],["SEO","Keyword research, on-page optimisation, technical review and content optimisation."],["Performance Marketing","Meta Ads, Google Ads, campaign structure, targeting and lead-gen planning."],["Content Marketing","Educational content, messaging, content pillars and clear calls to action."],["CRM & Lead Generation","Lead tracking, follow-ups, pipeline management and reporting."]];
const steps=["Research","Strategy","Create","Launch","Analyse","Optimise"];
export default function Home(){return(<>
<section className="bg-gradient-to-b from-mist to-white"><Wrap className="grid items-center gap-10 py-16 md:grid-cols-[1fr_280px] md:py-24"><div className="fade max-w-3xl">
<p className="text-sm font-semibold text-brand">{SITE.title}</p><h1 className="mt-3 text-4xl font-bold tracking-tight text-navy md:text-6xl">{SITE.name}</h1>
<p className="mt-4 text-xl text-ink md:text-2xl">I turn marketing ideas into content, campaigns and measurable growth.</p>
<p className="mt-4 text-slate-600">MBA in Marketing with a B.Tech in Computer Science. I plan and create social content, run SEO and paid search, and keep an eye on the numbers behind both.</p>
<p className="mt-3 text-sm text-slate-500">{SITE.tagline}</p>
<div className="mt-8 flex flex-wrap items-center gap-3"><Btn href="/work">View My Work</Btn><Btn href={SITE.resume} alt>Download Resume</Btn><a className="px-2 text-sm font-semibold text-brand hover:underline" href={SITE.linkedin} target="_blank" rel="noopener noreferrer">LinkedIn ↗</a></div></div><Image src="/arshdeep.webp" alt="Portrait of Arshdeep Singh" width={400} height={400} priority className="mx-auto w-48 rounded-2xl object-cover shadow-lg md:w-full"/></Wrap></section>
<Wrap className="py-16"><Heading eyebrow="What I work on" title="Creative enough to make good content. Analytical enough to check it worked."/>
<div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{services.map(([t,d])=><div key={t} className="rounded-xl border border-slate-200 p-5"><h3 className="font-semibold text-navy">{t}</h3><p className="mt-2 text-sm text-slate-600">{d}</p></div>)}</div></Wrap>
<Wrap className="py-8"><Heading eyebrow="Selected work" title="Five projects, each with the thinking behind it"/>
<div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">{projects.map((p,i)=><ProjectCard key={p.slug} p={p} n={i+1}/>)}</div></Wrap>
<Wrap className="py-16"><Heading eyebrow="Selected results" title="Numbers from my experience" sub="From my role as Digital Marketing Executive at SMSF Audits. These are role-level results, not tied to a single post or campaign."/>
<div className="grid gap-4 sm:grid-cols-3">{[["10+","target keywords with improved rankings"],["$2,000+","monthly Google Ads budget managed"],["45%","increase in organic traffic I contributed to"]].map(([n,l])=><div key={n} className="rounded-xl bg-navy p-6 text-white"><p className="text-4xl font-bold text-accent">{n}</p><p className="mt-2 text-sm text-slate-300">{l}</p></div>)}</div>
<p className="mt-4 text-sm text-slate-500">RentalEase and BrightMark are strategy and practice projects, so no live results are claimed for them.</p></Wrap>
<section className="bg-mist"><Wrap className="py-16"><Heading eyebrow="My approach" title="How I work on a campaign"/>
<ol className="grid grid-cols-2 gap-3 md:grid-cols-6">{steps.map((s,i)=><li key={s} className="rounded-lg bg-white p-4 text-center text-sm font-semibold text-navy shadow-sm"><span className="block text-xs text-brand">0{i+1}</span>{s}</li>)}</ol></Wrap></section>
<Wrap className="py-16"><div className="grid gap-10 md:grid-cols-2"><div><Heading eyebrow="About" title="Marketing with a technical head"/><p className="text-slate-600">I have an MBA in Marketing and a B.Tech in Computer Science. My work spans social media, SEO, Google and Meta Ads, lead generation and CRM. I like content that is clear and also tied to a business goal.</p><Link href="/about" className="mt-4 inline-block font-semibold text-brand">More about me →</Link></div>
<div><Heading eyebrow="Tools & skills" title="What I use"/><div className="flex flex-wrap gap-2">{Object.values(skills).flat().slice(0,16).map(s=><span key={s} className="rounded-full bg-mist px-3 py-1 text-sm">{s}</span>)}</div></div></div></Wrap>
<Wrap className="pb-8"><div className="rounded-2xl bg-navy p-10 text-center text-white"><h2 className="text-2xl font-bold">Looking for a digital marketer?</h2><p className="mt-2 text-slate-300">I'd be happy to talk about your team and what you need.</p><Link href="/contact" className="mt-6 inline-block rounded-lg bg-white px-5 py-3 text-sm font-semibold text-navy hover:bg-accent">Let's talk</Link></div></Wrap></>)}
