import Link from "next/link";import Image from "next/image";import {SITE,Project} from "@/lib/content";
export const Wrap=({children,className=""}:{children:React.ReactNode;className?:string})=><div className={`mx-auto max-w-6xl px-5 ${className}`}>{children}</div>;
export const Heading=({eyebrow,title,sub}:{eyebrow?:string;title:string;sub?:string})=><div className="mb-10 max-w-2xl">{eyebrow&&<p className="mb-2 text-xs font-semibold uppercase tracking-widest text-brand">{eyebrow}</p>}<h2 className="text-3xl font-bold tracking-tight text-navy">{title}</h2>{sub&&<p className="mt-3 text-slate-600">{sub}</p>}</div>;
export const Btn=({href,children,alt,ext}:{href:string;children:React.ReactNode;alt?:boolean;ext?:boolean})=><Link href={href} {...(ext?{target:"_blank",rel:"noopener noreferrer"}:{})} className={`inline-block rounded-lg px-5 py-3 text-sm font-semibold transition ${alt?"border border-slate-300 text-navy hover:border-navy":"bg-navy text-white hover:bg-brand"}`}>{children}</Link>;
export function ProjectCard({p,n}:{p:Project;n:number}){return(<Link href={`/work/${p.slug}`} className="group flex flex-col overflow-hidden rounded-xl border border-slate-200 bg-white transition hover:-translate-y-1 hover:shadow-lg">
<div className={`relative aspect-[4/3] ${p.contain?"bg-white":"bg-mist"}`}>{p.cover?<Image src={p.cover} alt={`${p.name} sample creative`} fill sizes="(min-width:768px) 33vw,100vw" className={p.contain?"object-contain p-8":"object-cover object-top"} loading="lazy"/>:<div className="h-full bg-navy"/>}</div>
<div className="flex flex-1 flex-col p-5"><p className="text-xs text-slate-500">Project {String(n).padStart(2,"0")} · {p.industry}</p><h3 className="mt-1 text-lg font-semibold text-navy">{p.name}</h3><p className="text-sm font-medium text-brand">{p.kind}</p><p className="mt-2 flex-1 text-sm text-slate-600">{p.summary}</p>
<p className="mt-3 text-xs text-slate-500">{p.services.join(" · ")}</p><span className="mt-4 text-sm font-semibold text-navy group-hover:text-brand">View Case Study →</span></div></Link>)}
export const Footer=()=><footer className="mt-24 bg-navy py-12 text-slate-300"><Wrap className="flex flex-col gap-6 md:flex-row md:justify-between"><div><p className="font-semibold text-white">{SITE.name}</p><p className="text-sm">{SITE.title}</p><p className="mt-1 text-sm text-slate-400">Social Media • Content • SEO • Performance Marketing</p></div>
<div className="text-sm"><a className="block hover:text-white" href={SITE.linkedin} target="_blank" rel="noopener noreferrer">LinkedIn</a><a className="block hover:text-white" href={`mailto:${SITE.email}`}>{SITE.email}</a><p className="mt-3 text-slate-400">© {new Date().getFullYear()} {SITE.name}</p></div></Wrap></footer>;
